
volumes:
  db-crud:

services:
  postgres-db-atv:
    image: postgres:14.13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud-basico
    ports:
      - 5432:5432
    volumes:
      - db-crud:/var/lib/postgresql